#! /bin/bash
if [ $# -eq 1 ]; then
	echo This args command has 1 argument.
	echo It is $1
elif [ $# -ne 0 ]; then
	echo This args command has $# arguments.
	echo They are $*
else echo This args command has 0 arguments.
fi
