#! /bin/bash
#! /bin/sh
if [ $# -ge 2 ]; then 
	sum=$(($1+$2))
	echo Sum of $1 and $2 is $sum
	exit
fi

read -p "Enter 2 numbers seperated by space:" n1 n2

if [ -z $n1 ] || [ -z $n2 ]; then
	echo Missing arguments.
else 
	sum=$((n1 + n2))
	echo Sum of $n1 and $n2 is $sum
fi
